# Generated by Django 5.0.3 on 2024-03-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmodel_delete_projectsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectModel',
            new_name='ProjectsModel',
        ),
    ]
