# Generated by Django 5.0.2 on 2024-03-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='second_name',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
